### ISSUE TITLE
[Evolutiva] Adicionar busca por id para o usuário

### ISSUE THREAD

**Issue by DavidBNeto** [DavidBNeto/flor-de-lotus-api#5]
Permitir saber o estado atual de um hive de drones facilitando assim saber quais estão ativos.

Possibilitar encontrar um usuário pelo seu ID, tornando possível recuperar um único usuário pelo seu ID, sem a necessidade de varrer o banco todo para isso.

**Comment by DMorsch** [comment]
Done.
